#ifndef ERROR_H
#define ERROR_H

#define ERROR_SMAKEFILE_NOT_FOUND 101
#define ERROR_TOO_MANY_EXEC 202
#define ERROR_NO_EXEC 303
#define ERROR_DIR_NOT_FOUND 404
#define ERROR_NO_SRC 505
#define ERROR_HEADER_NOT_FOUND 606
#define ERROR_SRC_NOT_FOUND 707
#define ERROR_EXEC_FAILED 808

#endif
